version: '3.9'

services:

  mongodb:
    build:
      context: mongo
      dockerfile: Dockerfile
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - robot-shop
    logging: &logging
      driver: json-file
      options:
        max-size: "25m"
        max-file: "2"

  redis:
    image: redis:6.2.13-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - robot-shop
    logging:
      <<: *logging

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672" # RabbitMQ dashboard
    networks:
      - robot-shop
    logging:
      <<: *logging

  catalogue:
    build:
      context: catalogue
      dockerfile: Dockerfile
    container_name: catalogue
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - robot-shop
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      <<: *logging

  user:
    build:
      context: user
      dockerfile: Dockerfile
    container_name: user
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
    networks:
      - robot-shop
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      <<: *logging

  cart:
    build:
      context: cart
      dockerfile: Dockerfile
    container_name: cart
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - robot-shop
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      <<: *logging

  mysql:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: mysql
    restart: unless-stopped
    env_file:
      - ./db/.env
    cap_add:
      - NET_ADMIN
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - robot-shop
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 10s
      retries: 5
    logging:
      <<: *logging

  shipping:
    build:
      context: shipping
      dockerfile: Dockerfile
    container_name: shipping
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - robot-shop
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      <<: *logging

  ratings:
    build:
      context: ratings
      dockerfile: Dockerfile
    container_name: ratings
    restart: unless-stopped
    environment:
      APP_ENV: dev
    depends_on:
      - mysql
    networks:
      - robot-shop
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/_health"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      <<: *logging

  payment:
    build:
      context: payment
      dockerfile: Dockerfile
    container_name: payment
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - robot-shop
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      <<: *logging

  dispatch:
    build:
      context: dispatch
      dockerfile: Dockerfile
    container_name: dispatch
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - robot-shop
    logging:
      <<: *logging

  web:
    build:
      context: web
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    depends_on:
      - catalogue
      - user
      - shipping
      - payment
    ports:
      - "8080:8080"
    networks:
      - robot-shop
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      <<: *logging

networks:
  robot-shop:
    driver: bridge

volumes:
  mongodb_data:
  mysql_data:
  rabbitmq_data:
  redis_data:

