name: Catalogue Service

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Git branch to deploy"
        required: true
        default: "main"
        type: string

      version:
        description: "Semantic version tag (example: v1.0.0)"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: catalogue

jobs:
  build:
    name: Build and Push Catalogue Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Validate version
        run: |
          VERSION="${{ github.event.inputs.version }}"
          if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set registry
        run: echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: |
          docker build \
            -t $ECR_REGISTRY/catalogue:$VERSION \
            .

      - name: Push image
        run: docker push $ECR_REGISTRY/catalogue:$VERSION